
bin_PROGRAMS += expand/btexpand

expand_btexpand_SOURCES = expand/hal/hal_ble.c \
						  expand/hal/hal_hw.c \
						  expand/hal/hal_flash.c \
						  expand/hal/hal_timer.c \
						  expand/hal/hal_watchdog.c \
						  expand/impl/advertising.c \
						  expand/imp/gatt.c \
						  expand/btexpand.c

expand_btexpand_LDADD = gdbus/libgdbus-internal.la src/libshared-glib.la \
				$(GLIB_LIBS) $(DBUS_LIBS) -lpthread


